[package]
name = "homechart-openapi-gen"
version = "2025.12.29+f7c74cd"
authors = ["OpenAPI Generator team and contributors"]
description = "_The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). "
# Override this license by providing a License Object in the OpenAPI.
license = "Unlicense"
edition = "2021"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = "^2.5"
uuid = { version = "^1.8", features = ["serde", "v4"] }
async-trait = "^0.1"
reqwest = { version = "^0.12", default-features = false, features = ["json", "multipart", "stream"] }
bon = { version = "2.3", optional = true }
[features]
default = ["native-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]
bon = ["dep:bon"]
